version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily"
    # Labels on pull requests for security and version updates
    labels:
      - "npm dependencies"
    pull-request-branch-name:
    # Separate sections of the branch name with a hyphen
      separator: "-"  
    # Prefix all commit messages with "npm"  
    commit-message:
      prefix: "npm"  
    # Allow up to 10 open pull requests for npm dependencies
    open-pull-requests-limit: 10
